language: node_js
node_js:
  - "stable"
services:
  - redis-server
os:
  - "linux"
  - "osx"
  - "windows"
addons:
  homebrew:
    packages: 
      - redis
    update: true
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then redis-server /usr/local/etc/redis.conf; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then redis-server --service-start; fi
