language: node_js
node_js:
  - "node"
services:
  - redis-server
os:
  - "linux"
  - "osx"
  - "windows"
addons:
  homebrew:
    packages: 
      - redis
    update: true
install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install redis-64; fi
  - npm install eslint --save-dev
script:
  - npm run lint -- --fix
  
