tls:
  certificates:
    # The path to certs specified here is just a placeholder.
    # During production deployment, it should be changed to `/certs/${PATH_TO_CERTS} (from .env)
    - certFile: /certs/path/to/certs
      keyFile: /certs/path/to/certs
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12

    mintls13:
      minVersion: VersionTLS13
